apiVersion: v1
kind: Service
metadata:
  name: simple-service
spec:
  type: LoadBalancer
  selector:
    app: trivial-go-web-app
  ports:
      - port: 80
        protocol: TCP
        targetPort: 9376
